# frontend/pubspec.yaml

name: bioinformatics_app
description: A full-stack bioinformatics application with Flutter frontend and FastAPI backend.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  file_picker: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
